### PR TITLE
v2

### LINKED ISSUE #13: Add appending option to tags
Let's say you build multiple distro flavors of your Docker image, e. g. one in Ubuntu (main) and one in Alpine.
Meanwhile it's fine to use the usual tagging for the main image, is there a way of setting a "base tag" or a "tag" to be appended? In this case, for the Alpine flavor, instead of `latest`, using `alpine`, `x.x.x-alpine` etc. is more appropriate.

### LINKED ISSUE #25: Handling short version tags
Following up on #20, how would you suggest to produce tags `v1`, `v1.6` and `latest` for `v1.6` tag? The `tag-match` option can only generate one tag in addition to `latest`.

### LINKED ISSUE #27: Select/Change order of tags.
If you have `latest` and/or `sha` tagging enabled, then they get pushed to the registry last. Due to how github treats the last image pushed as the "latest" one, it shows it as first in every list and reference to that package.

This can get very confusing if you are looking at a list of packages e.g. here: https://github.com/orgs/restorecommerce/packages

It would be great if the `latest` and `sha` tags would be first in the list of tagged images, and the semver ones last. You could also provide an option to toggle this functionality or even pick the order.

### LINKED ISSUE #30: Proposal: Redesign tagging input/outputs to be independent
I still use this action for labeling features, but if you're open to it, I'd really like you to consider importing my actions tag handling capabilities due to their power, simplicity, and flexibility.

To give you an example, here's a snippet from a repo where I'm using the latest functionality I've implemented, snippet pulled from https://github.com/OctoPrint/octoprint-docker/blob/master/.github/workflows/octoprint-release.yml#L69-L87:

```yaml
      -
        id: buildxy
        run: echo '::set-output name=buildxy::${{ (github.event.action == 'deploy'|| github.event.action == 'released') && github.event.client_payload.tag_name == steps.stable-octoprint.outputs.release }}'
      -
        name: Tagging Strategy
        id: tagging
        uses: HackerHappyHour/tagging-strategy@v3
        with:
          image_name: octoprint/octoprint
          tag_name: ${{ github.event.client_payload.tag_name }}
          tags: |
            %X%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y.Z%
          extra_tags: |
            latest::${{ steps.stable-octoprint.outputs.release == github.event.client_payload.tag_name }}
            edge::${{ github.event.action == 'prereleased' || github.event.client_payload.tag_name == steps.latest-octoprint.outputs.release }}
            canary::${{ github.event.action == 'canary' }}
            bleeding::${{ github.event.action == 'bleeding' }}
```

This one snippet demonstrates the how i think the approach to tagging should work in ghaction-dockermeta: 
 - explicit control over the conditions of each and every tag, 
- semver parsing
- no interdependent input parameters, 
- output compatible with docker/build-push-action
- supports tag suffixes #15
- supports additional non-semver custom tags #24 via `extra_tags`
- compatible with externally triggered events
- sha tags (via `extra_tags` parameter in a similar way to your `{{raw}}` usage

### Bonus

As far as I can tell, refactoring tag inputs to work as they do in HackerHappyHour/tagging-strategy@v3+ would close the following open issues as well:
- #29 (since the base tag input isn't resolved by the action but passed in by the user, the user can pass in whatever they want)
- #27 (simply changing the order in the `tags` or `extra_tags` of HackerHappyHour/tagging-strategy accomplishes this)
- #25 (you can see in the example above how HackerHappyHour/tagging-strategy already does this)
- #13 (HackerHappyHour/tagging-strategy already supports this, examples [here](https://github.com/marketplace/actions/tagging-strategy#variant),  [here](https://github.com/marketplace/actions/tagging-strategy#from-release-on-external-repository) and in the [testing fixtures](https://github.com/HackerHappyHour/tagging-strategy/blob/master/__tests__/__data__/taggingStrategy.js#L71-L72))

I doubt my action will ever get any users (even though I obviously have a super high opinion of it :smirk: ), but you've got the benefit of having been in the docker action space since actions launched, and the have visibility and reach. I'd love for the work I did to benefit your users and carry over here.

Would you be willing to consider a redesign to bring support for this usage technique?  I'd really love to be able to archive my project and merge it with yours!

### LINKED ISSUE #41: tag-latest: true not working
Please see this build as example:

https://github.com/felipecrs/jenkins-agent-dind/runs/1812044006

Despite docker-meta receives "tag-latest: true" as input, the only tags generated are "master".

Also reported it https://github.com/crazy-max/ghaction-docker-meta/issues/40 apparently.

### PR DESCRIPTION
**Pull request by crazy-max**
Fixes #30
Fixes #41
Fixes #13
Fixes #27
Fixes #25
Closes #47
Closes #15

v2 introduces a new way to handle metadata for your Docker image as part of the proposal in #30.
Documentation: https://github.com/crazy-max/ghaction-docker-meta/tree/v2#readme

cc. @LongLiveCHIEF @hugopeixoto @mblaschke @felipecrs @kereis @slimcdk @whyman @CharlieC3 @lpil

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
Still too tightly tied to explicit events. Decouple the events from the payload and things become even simpler, and far more versatile. 

This is too narrow of a use case. What if I'm tagging the image based on the version of the software inside of it, and not the version of the image itself? What If i'm building an image based on events in another repo?

This is way more complex than it needs to be. Look at my [current implementation](github.com/HackerHappyHour/tagging-strategy). 
- It can solve the primary use this action does where you tag something based on refs from the event types listed here.  
- It can produce every type of tag you are producing here, _without_ the complicated `type=` syntax.
- It can additionally support parsing of "raw" tags using semver, allowing both of the use cases I described above.

It does all that, just by simply allowing the user to input the ref instead of trying to determine what ref to use based on the event type.  

It's great how much this is thought through, but in the end, I think it's too over-engineered to be useful outside of a specific use-case, and _that's_ what my proposal was about.

**Comment by crazy-max** [comment]
@LongLiveCHIEF 

> Still too tightly tied to explicit events.

That's the purpose of this action, handle metadata through events triggered by the workflow.

> This is too narrow of a use case. What if I'm tagging the image based on the version of the software inside of it, and not the version of the image itself? What If i'm building an image based on events in another repo?

I think it's relative to your use case. Very few users that I know of use events with custom payloads but anyway it's still possible with v2:

```yaml
      -
        id: buildxy
        run: echo '::set-output name=buildxy::${{ (github.event.action == 'deploy'|| github.event.action == 'released') && github.event.client_payload.tag_name == steps.stable-octoprint.outputs.release }}'
      -
        name: Tagging Strategy
        id: tagging
        uses: HackerHappyHour/tagging-strategy@v3
        with:
          image_name: octoprint/octoprint
          tag_name: ${{ github.event.client_payload.tag_name }}
          tags: |
            %X%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y%::${{ steps.buildxy.outputs.buildxy }}
            %X.Y.Z%
          extra_tags: |
            latest::${{ steps.stable-octoprint.outputs.release == github.event.client_payload.tag_name }}
            edge::${{ github.event.action == 'prereleased' || github.event.client_payload.tag_name == steps.latest-octoprint.outputs.release }}
            canary::${{ github.event.action == 'canary' }}
            bleeding::${{ github.event.action == 'bleeding' }}
```

could be used like this with v2:

```yaml
      -
        id: buildxy
        run: echo '::set-output name=buildxy::${{ (github.event.action == 'deploy'|| github.event.action == 'released') && github.event.client_payload.tag_name == steps.stable-octoprint.outputs.release }}'
      -
        name: Meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: octoprint/octoprint
          tag_name: ${{ github.event.client_payload.tag_name }}
          tags: |
            ${{ github.event.client_payload.tag_name }}
            type=semver,pattern={{major}},enable=${{ steps.buildxy.outputs.buildxy }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ steps.buildxy.outputs.buildxy }}
            type=semver,pattern={{version}}
            type=raw,value=edge,enable=${{ github.event.action == 'prereleased' || github.event.client_payload.tag_name == steps.latest-octoprint.outputs.release }}
            type=raw,value=canary,enable=${{ github.event.action == 'canary' }}
            type=raw,value=bleeding,enable=${{ github.event.action == 'bleeding' }}
          flavor: |
            latest=${{ steps.stable-octoprint.outputs.release == github.event.client_payload.tag_name }}
```

> I think it's too over-engineered to be useful outside of a specific use-case, and that's what my proposal was about.

I rather think that your workflow in the above example is too complex and does not reflect a nominal case where a user simply wants to release his Docker image following a standard GitFlow (push, tag). But again you can do that with v2 if you want.

If you have a use case where v2 would not be effective I would be happy to review its structure. Thanks again for your feedback!

**Comment by LongLiveCHIEF** [comment]
Your example doesn't work.  The first entry in tags is just a raw tag, and isn't parsed at all.  The other entries presume there is a corresponding ref, which the workflow wouldn't have, and thus would fail.

let's say i get a `github.event.client_payload.tag_name` value of `2.0.0`.  I want to produce the tags `image:2.0.0`, `image:2.0`, `image:2`.

I _can't_ do this with the v1 implementation of your action, _or_ the v2 implementation as its currently written.

> Very few users that I know of use events with custom payloads

I can tell you've been in this business as long as I have, and undoubtedly have learned by now that this is a trap. :smirk: 

Use cases where you'd want to use external payloads:
- creating an organization specific customization of a base image. say to do things like modify environment variables or trusted certificates for the base image so that it works inside your organizations networks as a drop-in replacement for the base image
- you maintain a fork of a product with your own customizations to the software
- The container deployment of a product has it's own development lifecycle and is thus maintained in a different repo than the software it packages.

> I rather think that your workflow in the above example is too complex and does not reflect a nominal case where a user simply wants to release his Docker image following a standard GitFlow

I think it would be very simple to maintain this behavior as the default, and implement the ability to parse `type=raw` in a future feature. If this is the case, v2.0 is just a migration to the action usage, and future versions would build on that with new features.

---

I also still wonder if `type=` is actually needed?  See my thoughts on that in [my comment on the proposal thread](https://github.com/crazy-max/ghaction-docker-meta/issues/30#issuecomment-803626719)

**Comment by crazy-max** [comment]
@LongLiveCHIEF 

> The first entry in tags is just a raw tag, and isn't parsed at all.

No it will be parsed as a `type=raw` if no type is defined: https://github.com/crazy-max/ghaction-docker-meta/tree/v2#typeraw

```yaml
tags: |
  type=raw,value=mytag1
  # or
  type=raw,mytag1
  # or
  mytag1
```

> let's say i get a `github.event.client_payload.tag_name` value of `2.0.0`. I want to produce the tags `image:2.0.0`, `image:2.0`, `image:2`.

Agree about this one, semver will not be processed because it's not a tag event. I will improve this behavior.

> Use cases where you'd want to use external payloads...

I'm fine with that, I'm going to make some changes in that direction.

**Comment by LongLiveCHIEF** [comment]
Based on your latest comments, I believe my primary concerns are resolved at least for the moment, and I agree with this direction. At this point I'm going with :thumbsup: based on the docs. 

While not a full replacement yet, it does give me a path to deprecate my own action as those improvements you mentioned are rolled out, and I'd be happy to contribute those features and join you as a maintainer for this project if you want that.

**Comment by crazy-max** [comment]
@LongLiveCHIEF 

> While not a full replacement yet, it does give me a path to deprecate my own action as those improvements you mentioned are rolled out

Sure we can bring enhancements in folllow up PRs. Just want with v2 a solid foundation to build on.

> I'd be happy to contribute those features and join you as a maintainer for this project if you want that.

Ofc with pleasure!

**Comment by crazy-max** [comment]
@LongLiveCHIEF Ok now you can use a custom value for [semver](https://github.com/crazy-max/ghaction-docker-meta/tree/v2#typesemver) and [match](https://github.com/crazy-max/ghaction-docker-meta/tree/v2#typematch) type.

**Comment by MarcelCoding** [comment]
Maybe I am to stupid, but I am not able to use the branch name as tag and on the default branch `edge` as tag. In the default branch the tag `<default_branch>` will be also created.

**Comment by crazy-max** [comment]
@MarcelCoding Can you create a [new issue](https://github.com/crazy-max/ghaction-docker-meta/issues/new?assignees=&labels=&template=bug_report.md) please? I would need logs and link to your repo/pipeline. Thanks.

**Comment by MarcelCoding** [comment]
@crazy-max https://github.com/crazy-max/ghaction-docker-meta/issues/55

**Pull request merged**
